### PR TITLE
[DCJ-400-gradle] Upgrade io.swagger.codegen.v3 deps 3.0.61 -> 3.0.62

### PR DESCRIPTION
**Pull request by okotsopoulos**
__Jira ticket__: https://broadworkbench.atlassian.net/browse/DCJ-400

## Addresses

This patch upgrade without changing configuration caused compilation of Swagger generated code to fail with the following errors:

```
/github/workspace/build/generated-src/swagger/src/main/java/bio/terra/model/ResourcePolicyModel.java:10: error: package io.swagger.configuration does not exist
import io.swagger.configuration.NotUndefined;
                               ^
/github/workspace/build/generated-src/swagger/src/main/java/bio/terra/model/ResourcePolicyModel.java:21: error: cannot find symbol
@NotUndefined
 ^
```

This was introduced in https://github.com/swagger-api/swagger-codegen-generators/pull/1308

## Summary of changes

- Upgrade `io.swagger.codegen.v3:swagger-codegen` and `io.swagger.codegen.v3:swagger-codegen-cli` from 3.0.61 -> 3.0.62
- For the time being, set `validationMode=legacy` along with these patch upgrades to mitigate another likely bug in swagger-codegen-generators.
- Because `io.swagger.codegen.v3` patch upgrades have lately included breaking changes, exclude them from our grouped minor and patch upgrade Dependabot PRs.  Any available upgrades will be PRed separately. 

## Testing Strategy

CI build and tests should pass.

### CODE REVIEW

**Review by fboulnois — APPROVED** [review]
thanks for catching this 👍

**Review by rushtong — APPROVED** [review]
👍🏽
